[general]
import = [
    "~/.config/alacritty/themes/themes/xterm.toml"
]

[window]
dimensions = {columns = 150, lines = 48}
#decorations = "None"
#startup_mode = "Maximized"
decorations_theme_variant = "Dark"
padding = {x = 3, y = 3}

[scrolling]
history = 65000

[font]
normal = {family = "monospace", style = "Regular"}
size = 14
