import = [
    "~/.config/alacritty/themes/tender.toml"
]

[scrolling]
history = 100000

[font]
size = 16.5

[font.normal]
family = "Cousine Nerd Font"

[window]
decorations = "None"
startup_mode = "Maximized"
#decorations_theme_variant = "Dark"

#[window.dimensions]
#columns = 152
#lines = 48
