[colors.primary]
background = "#2E3436"
foreground = "#D3D7CF"

[colors.normal]
black = "#171421"
blue = "#12488B"
cyan = "#2AA1B3"
green = "#26A269"
magenta = "#A347BA"
red = "#C01C28"
white = "#D0CFCC"
yellow = "#A2734C"

[colors.bright]
black = "#5E5C64"
blue = "#2A7BDE"
cyan = "#33C7DE"
green = "#33D17A"
magenta = "#C061CB"
red = "#F66151"
white = "#FFFFFF"
yellow = "#E9AD0C"
